### ISSUE TITLE
Operator namespace name label for network policies missing

### ISSUE THREAD

**Issue by megian** [appuio/component-openshift4-operators#2]
The version v1.0.0 does not set a name label. This is required for the network policies created in openshift4-logging.

The namespace can be manually labeled, in example:
```
oc label ns openshift-operators-redhat name=openshift-operators-redhat
```

## Steps to Reproduce the Problem

  1. Create a new cluster
  1. Deploy openshift-operators as openshift-operators-redhat
  1. No name label is set

## Actual Behavior
No name label is set.

## Expected Behavior
There must be a name label name=${name of instance}

**Comment by simu** [comment]
Can't reproduce this, when compiling the component the resulting namespace object does have label `name`:

```
$ cat catalog/manifests/openshift4-operators/openshift-operators-redhat.yaml 
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ''
  labels:
    name: openshift-operators-redhat
    openshift.io/cluster-monitoring: true
  name: openshift-operators-redhat
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations: {}
  labels:
    name: openshift-operators-redhat
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
```
